# Generated by Django 5.1 on 2024-11-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m4h', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cod_parafa',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cod_parafa',
            field=models.CharField(blank=True, default='000000', max_length=6, null=True),
        ),
    ]
