# Generated by Django 5.1b1 on 2024-08-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m4h', '0002_profile_email_profile_id_doctor_profile_last_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('pacient', 'Pacient'), ('doctor', 'Doctor')], default='pacient', max_length=20),
        ),
    ]
