# Generated by Django 5.1b1 on 2024-08-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m4h', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_doctor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AlterField(
            model_name='profile',
            name='adresa',
            field=models.CharField(default='Necunoscut', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nume',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prenume',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('pacient', 'Pacient')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefon',
            field=models.CharField(default='Necunoscut', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='varsta',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
