# Generated by Django 5.1b1 on 2024-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m4h', '0004_remove_profile_id_doctor_remove_profile_last_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='varsta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
