# Generated by Django 5.1b1 on 2024-08-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m4h', '0005_alter_profile_varsta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacient', to='m4h.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('pacient', 'Pacient')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
